#!/usr/bin/env python3
"""mksyms.py -- publish an image's equates to its Lua harness.

emu/latency.lua arrived from a sibling carrying `local VOST, VOERR, VOFCNT =
0xF7, 0xD5, 0xFA` and a comment saying to keep them in step with the assembly
by hand. They were not in step: this port moved the probe's counters off the
top of RAM -- a probe that puts its counters under the stack measures how deep
it nested -- and the harness went on tapping the old cells and reporting zero
rounds while 588 of them completed.

Nothing was wrong with the ROM and nothing was wrong with the harness. The two
simply disagreed, and neither could tell. So the addresses are generated from
the assembler's own listing and the harness loads them.

Usage: mksyms.py <listing.lst> <out.lua> NAME [NAME ...]
"""
import re
import sys


def main():
    lst, out, names = sys.argv[1], sys.argv[2], sys.argv[3:]
    want = set(names)
    found = {}
    pat = re.compile(r'=\$([0-9A-F]+)\s+(\w+)\s+EQU', re.I)
    for ln in open(lst, errors='replace'):
        m = pat.search(ln)
        if m and m.group(2) in want:
            found.setdefault(m.group(2), int(m.group(1), 16))
    missing = sorted(want - set(found))
    if missing:
        sys.exit("mksyms: %s not found in %s" % (", ".join(missing), lst))
    with open(out, "w") as f:
        f.write("-- generated by tools/mksyms.py from %s -- do not edit\n" % lst)
        f.write("return {\n")
        for k in sorted(found):
            f.write("    %s = 0x%02X,\n" % (k, found[k]))
        f.write("}\n")
    print("mksyms: %s -> %s (%s)"
          % (lst, out, ", ".join("%s=$%02X" % (k, found[k])
                                 for k in sorted(found))))


if __name__ == '__main__':
    main()
